spring:
  application:
    name: hunglpmockjava
  datasource:
    url: jdbc:mysql://localhost:3306/java-learn
    username: javalearn
    password: javalearn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  messages:
    encoding: UTF-8
    basename: messages
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationThatIsLongEnoughForHMACSHA256Algorithm
    expiration: 86400000 # 24 hours

# Google OAuth2 Configuration
google:
  oauth2:
    client-id: xxxxxx
    client-secret: xxxxxx

springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
